#Query 1
PREFIX : <file:Lattes_KG#>
SELECT ?orientacao
WHERE {
  ?pesquisador :Nome "Gisele da Silva Craveiro" .
  ?pesquisador :orienta ?orientacao .
}

#Query 2
PREFIX : <file:Lattes_KG#>
SELECT ?pais (COUNT(?pesquisador) AS ?totalPesquisadores)
WHERE {
  ?pesquisador a :Pesquisador.
  ?pesquisador :Pais ?pais.
}
GROUP BY ?pais
ORDER BY DESC(?totalPesquisadores)


#Query 3
PREFIX : <file:Lattes_KG#>
SELECT DISTINCT ?pesquisador1 ?pesquisador2 ?instituicao
WHERE {
  ?pesquisador1 :possui_formacao ?formacao1 .
  ?pesquisador2 :possui_formacao ?formacao2 .
  ?formacao1 :Instituicao ?instituicao .
  FILTER (?pesquisador1 != ?pesquisador2)
}

#extra queries

PREFIX : <file:Lattes_KG#>
SELECT ?instituicao (COUNT(?orientacao) AS ?totalOrientacoes)
WHERE {
  ?pesquisador a :Pesquisador.
  ?pesquisador :orienta ?orientacao.
  ?orientacao :Instituicao ?instituicao.
}
GROUP BY ?instituicao
ORDER BY DESC(?totalOrientacoes)


PREFIX : <file:Lattes_KG#>
SELECT ?pesquisador ?tipoTrabalho
WHERE {
  ?pesquisador a :Pesquisador.
  ?pesquisador :orienta ?orientacao.
  ?orientacao :TipoTrabalho ?tipoTrabalho.
}


PREFIX : <file:Lattes_KG#>
SELECT ?pesquisador ?tipoTrabalho (COUNT(?tipoTrabalho) AS ?totalTiposTrabalho)
WHERE {
  ?pesquisador a :Pesquisador.
  ?pesquisador :orienta ?orientacao.
  ?orientacao :TipoTrabalho ?tipoTrabalho.
}
GROUP BY ?pesquisador ?tipoTrabalho
ORDER BY ?pesquisador ?tipoTrabalho

PREFIX : <file:Lattes_KG#>
SELECT ?pesquisador ?formacao ?titulo
WHERE {
  ?pesquisador a :Pesquisador.
  ?pesquisador :possui_formacao ?formacao.
  ?formacao :Titulo ?titulo
}


PREFIX : <file:Lattes_KG#>
SELECT  ?pesquisador ?orientacao
WHERE {
  ?pesquisador :Nome "Gisele da Silva Craveiro" .
  ?pesquisador :orienta ?orientacao .
}